name: ABChat
main: cn.douaol.abchat.Main
author: Douaol
version: 1.1.2
api-version: 1.13
softdepend: [PlaceholderAPI, Vault]
description: A chat management plugin for bukkit.
commands:
  abchat:
    aliases: [abc, chat]
permissions:
  abchat.use:
    default: op
  abchat.bypass.adv:
    default: op
  abchat.bypass.globalmute:
    default: op
  abchat.bypass.delay:
    default: op