name: ABChat
main: cn.douaol.abchat.Main
author: Douaol
version: 1.1-SNAPSHOT
api-version: 1.13
softdepend: [PlaceholderAPI]
description: A plugin that helps you block swearing.
commands:
  abchat:
    aliases: [abc, chat]
permissions:
  abchat.use:
    default: op
  abchat.bypass.adv:
    default: op
  abchat.bypass.globalmute:
    default: op
  abchat.bypass.delay:
    default: op
  abchat.bypass.global:
    default: op
